ZO_CreateStringId("SI_BINDING_NAME_ACTIVATE_PROFILE_1", PALocale.getResourceMessage("KB_Load_Profile1"))
ZO_CreateStringId("SI_BINDING_NAME_ACTIVATE_PROFILE_2", PALocale.getResourceMessage("KB_Load_Profile2"))
ZO_CreateStringId("SI_BINDING_NAME_ACTIVATE_PROFILE_3", PALocale.getResourceMessage("KB_Load_Profile3"))
ZO_CreateStringId("SI_BINDING_NAME_ACTIVATE_PROFILE_4", PALocale.getResourceMessage("KB_Load_Profile4"))
ZO_CreateStringId("SI_BINDING_NAME_ACTIVATE_PROFILE_5", PALocale.getResourceMessage("KB_Load_Profile5"))