if ResourceBundle == nil then ResourceBundle = {} end
if ResourceBundle.en == nil then ResourceBundle.en = {} end

-- PABanking
ResourceBundle.en["ItemType_None"] = "-"
ResourceBundle.en["ItemType_Deposit"] = "Deposit"
ResourceBundle.en["ItemType_Withdrawal"] = "Withdraw"

ResourceBundle.en["Hireling_Blacksmith"] = "Blacksmith"
ResourceBundle.en["Hireling_Clothier"] = "Clothier"
ResourceBundle.en["Hireling_Enchanter"] = "Enchanter"
ResourceBundle.en["Hireling_Woodworker"] = "Woodworker"

-- Item Types
ResourceBundle.en[ITEMTYPE_ADDITIVE] = "enITEMTYPE_ADDITIVE"
ResourceBundle.en[ITEMTYPE_ALCHEMY_BASE] = "Solvent (Alchemy)"
ResourceBundle.en[ITEMTYPE_ARMOR] = "Armor (any)"
ResourceBundle.en[ITEMTYPE_ARMOR_BOOSTER] = "enITEMTYPE_ARMOR_BOOSTER"
ResourceBundle.en[ITEMTYPE_ARMOR_TRAIT] = "Armor Trait"
ResourceBundle.en[ITEMTYPE_AVA_REPAIR] = "enITEMTYPE_AVA_REPAIR"
ResourceBundle.en[ITEMTYPE_BLACKSMITHING_BOOSTER] = "Temper (Blacksmithing)"
ResourceBundle.en[ITEMTYPE_BLACKSMITHING_MATERIAL] = "Material (Blacksmithing)"
ResourceBundle.en[ITEMTYPE_BLACKSMITHING_RAW_MATERIAL] = "Raw Material (Blacksmithing)"
ResourceBundle.en[ITEMTYPE_CLOTHIER_BOOSTER] = "Tannin (Clothing)"
ResourceBundle.en[ITEMTYPE_CLOTHIER_MATERIAL] = "Material (Clothing)"
ResourceBundle.en[ITEMTYPE_CLOTHIER_RAW_MATERIAL] = "Raw Material (Clothing)"
ResourceBundle.en[ITEMTYPE_COLLECTIBLE] = "enITEMTYPE_COLLECTIBLE"
ResourceBundle.en[ITEMTYPE_CONTAINER] = "Container"
ResourceBundle.en[ITEMTYPE_COSTUME] = "Costume"
ResourceBundle.en[ITEMTYPE_DISGUISE] = "enITEMTYPE_DISGUISE"
ResourceBundle.en[ITEMTYPE_DRINK] = "enITEMTYPE_DRINK"
ResourceBundle.en[ITEMTYPE_ENCHANTING_RUNE] = "Runestone (Enchanting)"
ResourceBundle.en[ITEMTYPE_ENCHANTMENT_BOOSTER] = "enITEMTYPE_ENCHANTMENT_BOOSTER"
ResourceBundle.en[ITEMTYPE_FLAVORING] = "enITEMTYPE_FLAVORING"
ResourceBundle.en[ITEMTYPE_FOOD] = "enITEMTYPE_FOOD"
ResourceBundle.en[ITEMTYPE_GLYPH_ARMOR] = "Armor Glyph (Enchanting)"
ResourceBundle.en[ITEMTYPE_GLYPH_JEWELRY] = "enITEMTYPE_GLYPH_JEWELRY"
ResourceBundle.en[ITEMTYPE_GLYPH_WEAPON] = "enITEMTYPE_GLYPH_WEAPON"
ResourceBundle.en[ITEMTYPE_INGREDIENT] = "Ingredient (Provisioning)"
ResourceBundle.en[ITEMTYPE_LOCKPICK] = "enITEMTYPE_LOCKPICK"
ResourceBundle.en[ITEMTYPE_LURE] = "enITEMTYPE_LURE"
ResourceBundle.en[ITEMTYPE_NONE] = "enITEMTYPE_NONE"
ResourceBundle.en[ITEMTYPE_PLUG] = "enITEMTYPE_PLUG"
ResourceBundle.en[ITEMTYPE_POISON] = "enITEMTYPE_POISON"
ResourceBundle.en[ITEMTYPE_POTION] = "Potion"
ResourceBundle.en[ITEMTYPE_RAW_MATERIAL] = "enITEMTYPE_RAW_MATERIAL"
ResourceBundle.en[ITEMTYPE_REAGENT] = "Reagent (Alchemy)"
ResourceBundle.en[ITEMTYPE_RECIPE] = "enITEMTYPE_RECIPE"
ResourceBundle.en[ITEMTYPE_SCROLL] = "enITEMTYPE_SCROLL"
ResourceBundle.en[ITEMTYPE_SIEGE] = "enITEMTYPE_SIEGE"
ResourceBundle.en[ITEMTYPE_SOUL_GEM] = "Soul Gem"
ResourceBundle.en[ITEMTYPE_SPICE] = "enITEMTYPE_SPICE"
ResourceBundle.en[ITEMTYPE_STYLE_MATERIAL] = "Style Material"
ResourceBundle.en[ITEMTYPE_TABARD] = "enITEMTYPE_TABARD"
ResourceBundle.en[ITEMTYPE_TOOL] = "Tool"
ResourceBundle.en[ITEMTYPE_TRASH] = "enITEMTYPE_TRASH"
ResourceBundle.en[ITEMTYPE_TROPHY] = "Trophy"
ResourceBundle.en[ITEMTYPE_WEAPON] = "enITEMTYPE_WEAPON"
ResourceBundle.en[ITEMTYPE_WEAPON_BOOSTER] = "enITEMTYPE_WEAPON_BOOSTER"
ResourceBundle.en[ITEMTYPE_WEAPON_TRAIT] = "Weapon Trait"
ResourceBundle.en[ITEMTYPE_WOODWORKING_BOOSTER] = "Resin (Woodworking)"
ResourceBundle.en[ITEMTYPE_WOODWORKING_MATERIAL] = "Material (Woodworking)"
ResourceBundle.en[ITEMTYPE_WOODWORKING_RAW_MATERIAL] = "Raw Material (Woodworking)"
