if ResourceBundle == nil then ResourceBundle = {} end
if ResourceBundle.en == nil then ResourceBundle.en = {} end

-- Welcome Messages --								-- Type '/pa' for GUI."
ResourceBundle.en["Welcome_NoSupport"] 				= PAC_COL_YELLOW.."P"..PAC_COL_WHITE.."ersonal"..PAC_COL_YELLOW.."A"..PAC_COL_WHITE.."ssistant"..PAC_COL_YELLOW.." at your service!   -   no localization for (%s) available yet."
ResourceBundle.en["Welcome_Support"] 				= PAC_COL_YELLOW.."P"..PAC_COL_WHITE.."ersonal"..PAC_COL_YELLOW.."A"..PAC_COL_WHITE.."ssistant"..PAC_COL_YELLOW.." at your service!"

-- PARepair --
ResourceBundle.en["PAR_FullRepair"] 				= "PARepair: All %s items repaired for %d gold."
ResourceBundle.en["PAR_PartialRepair"] 				= "PARepair: %d / %d %s items repaired for %d gold. (not enough gold)"
ResourceBundle.en["PAR_NoGoldToRepair"] 			= "PARepair: Not enough gold to repair %d %s items."
ResourceBundle.en["PAR_NoRepair"] 					= "PARepair: Nothing to repair."

-- PABanking --
ResourceBundle.en["PAB_GoldDepositet"] 				= "PABanking: %d gold deposited."
ResourceBundle.en["PAB_GoldWithdrawn"] 				= "PABanking: %d gold withdrawn."
ResourceBundle.en["PAB_GoldWithdrawnInsufficient"] 	= "PABanking: %d / %d gold withdrawn. (not enough gold in bank!)"

ResourceBundle.en["PAB_ItemMovedTo"] 				= "%d x %s was moved to %s."
ResourceBundle.en["PAB_ItemNotMovedTo"] 			= "%d x %s was NOT moved to %s."
ResourceBundle.en["PAB_ItemMovedToFailed"] 			= "FAILURE: %s could NOT be moved to %s."

ResourceBundle.en["PAB_NoSpaceInFor"] 				= "PABanking: Not enough space in %s for: %s"
ResourceBundle.en["PAB_NoSpaceToOpen"] 				= "PABanking: Not enough space in %s to open %s."
ResourceBundle.en["PAB_NoDeposit"] 					= "PABanking: Nothing to deposit."

ResourceBundle.en["PAB_ItemType_None"] 				= "-"
ResourceBundle.en["PAB_ItemType_Deposit"]			= "Deposit"
ResourceBundle.en["PAB_ItemType_Withdrawal"]		= "Withdraw"

ResourceBundle.en["PAB_Hireling_UseItem"] 			= "PABanking: Opening %s."
ResourceBundle.en["PAB_Hireling_Blacksmith"] 		= "Blacksmith"
ResourceBundle.en["PAB_Hireling_Clothier"] 			= "Clothier"
ResourceBundle.en["PAB_Hireling_Enchanter"] 		= "Enchanter"
ResourceBundle.en["PAB_Hireling_Woodworker"] 		= "Woodworker"

-- MainMenu --
ResourceBundle.en["MMenu_Title"] 					= "|cFFD700P|rersonal|cFFD700A|rssistant"

-- PARMenu --
ResourceBundle.en["PARMenu_Header"] 				= "|cFFD700PA R|repair"
ResourceBundle.en["PARMenu_Enable"] 				= "|cB0B0FFEnable Auto Repair|r"
ResourceBundle.en["PARMenu_Enable_T"] 				= "Enable Auto Repair?"
ResourceBundle.en["PARMenu_RepairEq"] 				= "Repair equipped items"
ResourceBundle.en["PARMenu_RepairEq_T"] 			= "Repair equipped items?"
ResourceBundle.en["PARMenu_RepairEqDura"] 			= "- Durability threshold in %"
ResourceBundle.en["PARMenu_RepairEqDura_T"] 		= "Repair equipped items only if they are at or below the defined durability threshold."
ResourceBundle.en["PARMenu_RepairBa"]				= "Repair backpack items"
ResourceBundle.en["PARMenu_RepairBa_T"] 			= "Repair items in you backpack?"
ResourceBundle.en["PARMenu_RepairBaDura"] 			= "- Durability threshold in %"
ResourceBundle.en["PARMenu_RepairBaDura_T"] 		= "Repair items in the backpack only if they are at or below the defined durability threshold."
ResourceBundle.en["PARMenu_HideNoRepair"] 			= "Hide 'Nothing to Repair' message"
ResourceBundle.en["PARMenu_HideNoRepair_T"] 		= "Hide 'Nothing to Repair' message. You will still see a message if there is something to repair."
ResourceBundle.en["PARMenu_HideAll"] 				= "Hide ALL messages"
ResourceBundle.en["PARMenu_HideAll_T"] 				= "Silent-Mode: no message will be displayed. You also won't see your repair cost."

-- PABMenu --
ResourceBundle.en["PABMenu_Header"] 				= "|cFFD700PA B|ranking"
ResourceBundle.en["PABMenu_Enable"] 				= "|cB0B0FFEnable Auto Banking|r"
ResourceBundle.en["PABMenu_Enable_T"] 				= "Enable Auto Bank Deposit and Withdrawal?"
ResourceBundle.en["PABMenu_DepGold"] 				= "Deposit Gold"
ResourceBundle.en["PABMenu_DepGold_T"] 				= "Auto deposit gold to bank?"
ResourceBundle.en["PABMenu_DepInterval"] 			= "- Min interval between deposits (sec)"
ResourceBundle.en["PABMenu_DepInterval_T"] 			= "Minimum time in seconds between two automatic gold deposits."
ResourceBundle.en["PABMenu_DepInterval_W"] 			= "Invalid number --> No minimum interval between deposits."
ResourceBundle.en["PABMenu_DepGoldPerc"] 			= "- Gold to deposit in %"
ResourceBundle.en["PABMenu_DepGoldPerc_T"] 			= "Maximum percentage of your current gold to be deposited."
ResourceBundle.en["PABMenu_DepGoldSteps"] 			= "- Gold transactions in steps of "
ResourceBundle.en["PABMenu_DepGoldSteps_T"] 		= "In what steps shall gold be deposited and withdrawn?"
ResourceBundle.en["PABMenu_DepGoldKeep"] 			= "- Min gold to keep on character"
ResourceBundle.en["PABMenu_DepGoldKeep_T"] 			= "Minimum amount of gold to always keep on the character."
ResourceBundle.en["PABMenu_DepGoldKeep_W"] 			= "Invalid number --> No gold shall be kept on the character."
ResourceBundle.en["PABMenu_WitGoldMin"] 			= "- Withdraw gold if below minimum"
ResourceBundle.en["PABMenu_WitGoldMin_T"] 			= "Automatically withdraw gold from the bank if there is less gold on the character than defined above?"
ResourceBundle.en["PABMenu_DepWitItem"] 			= "Deposit and withdraw Items"
ResourceBundle.en["PABMenu_DepWitItem_T"] 			= "Auto deposit and/or withdraw items to and from the bank?"
ResourceBundle.en["PABMenu_OpenHireling"] 			= "- Open Hireling Chests before deposit"
ResourceBundle.en["PABMenu_OpenHireling_T"] 		= "Shall the chests sent to you by hirelings automatically be opened before the item deposit starts?"
ResourceBundle.en["PABMenu_DepItemType"] 			= "- Set items to deposit/withdraw"
ResourceBundle.en["PABMenu_DepItemType_T"] 			= "Open the sub-menu to define for each item type whether it shall be deposited, withdrew or ignored."
ResourceBundle.en["PABMenu_DepItemJunk"] 			= "- Deposit items marked as junk"
ResourceBundle.en["PABMenu_DepItemJunk_T"] 			= "Shall items that are marked as junk be deposited to the bank as well?"
ResourceBundle.en["PABMenu_HideNoDeposit"] 			= "Hide 'Nothing to Deposit' message"
ResourceBundle.en["PABMenu_HideNoDeposit_T"] 		= "Hide 'Nothing to Deposit' message. You will see a message if there is something to deposit, though."
ResourceBundle.en["PABMenu_HideAll"] 				= "Hide ALL messages"
ResourceBundle.en["PABMenu_HideAll_T"] 				= "Silent-Mode: no message will be displayed. You also won't see your deposited gold/items."
ResourceBundle.en["PABMenu_DepButton"] 				= "Deposit all"
ResourceBundle.en["PABMenu_DepButton_T"] 			= "Change all dropdown values to 'Deposit'? |cff0000(will force a ReloadUI)|r"
ResourceBundle.en["PABMenu_DepButton_W"] 			= "Will force a ReloadUI."
ResourceBundle.en["PABMenu_WitButton"] 				= "Withdraw all"
ResourceBundle.en["PABMenu_WitButton_T"] 			= "Change all dropdown values to 'Withdraw'? |cff0000(will force a ReloadUI)|r"
ResourceBundle.en["PABMenu_WitButton_W"] 			= "Will force a ReloadUI."
ResourceBundle.en["PABMenu_IgnButton"] 				= "Ignore all"
ResourceBundle.en["PABMenu_IgnButton_T"] 			= "Change all dropdown values to '-'? |cff0000(will force a ReloadUI)|r"
ResourceBundle.en["PABMenu_IgnButton_W"] 			= "Will force a ReloadUI." 

-- Name Spaces --
ResourceBundle.en["NS_Bag_Equipped"]				= "equipped"
ResourceBundle.en["NS_Bag_Backpack"]				= "backpack"
ResourceBundle.en["NS_Bag_Bank"]					= "bank"
ResourceBundle.en["NS_Bag_Unknown"]					= "unknown"

-- Item Types --
ResourceBundle.en[ITEMTYPE_ADDITIVE] 				= "enITEMTYPE_ADDITIVE"
ResourceBundle.en[ITEMTYPE_ALCHEMY_BASE] 			= "Solvent (Alchemy)"
ResourceBundle.en[ITEMTYPE_ARMOR] 					= "Armor (any)"
ResourceBundle.en[ITEMTYPE_ARMOR_BOOSTER] 			= "enITEMTYPE_ARMOR_BOOSTER"
ResourceBundle.en[ITEMTYPE_ARMOR_TRAIT] 			= "Armor Trait"
ResourceBundle.en[ITEMTYPE_AVA_REPAIR] 				= "enITEMTYPE_AVA_REPAIR"
ResourceBundle.en[ITEMTYPE_BLACKSMITHING_BOOSTER] 	= "Temper (Blacksmithing)"
ResourceBundle.en[ITEMTYPE_BLACKSMITHING_MATERIAL] 	= "Material (Blacksmithing)"
ResourceBundle.en[ITEMTYPE_BLACKSMITHING_RAW_MATERIAL] = "Raw Material (Blacksmithing)"
ResourceBundle.en[ITEMTYPE_CLOTHIER_BOOSTER] 		= "Tannin (Clothing)"
ResourceBundle.en[ITEMTYPE_CLOTHIER_MATERIAL] 		= "Material (Clothing)"
ResourceBundle.en[ITEMTYPE_CLOTHIER_RAW_MATERIAL] 	= "Raw Material (Clothing)"
ResourceBundle.en[ITEMTYPE_COLLECTIBLE] 			= "enITEMTYPE_COLLECTIBLE"
ResourceBundle.en[ITEMTYPE_CONTAINER] 				= "Container"
ResourceBundle.en[ITEMTYPE_COSTUME] 				= "Costume"
ResourceBundle.en[ITEMTYPE_DISGUISE] 				= "enITEMTYPE_DISGUISE"
ResourceBundle.en[ITEMTYPE_DRINK] 					= "enITEMTYPE_DRINK"
ResourceBundle.en[ITEMTYPE_ENCHANTING_RUNE] 		= "Runestone (Enchanting)"
ResourceBundle.en[ITEMTYPE_ENCHANTMENT_BOOSTER] 	= "enITEMTYPE_ENCHANTMENT_BOOSTER"
ResourceBundle.en[ITEMTYPE_FLAVORING] 				= "enITEMTYPE_FLAVORING"
ResourceBundle.en[ITEMTYPE_FOOD] 					= "Food"
ResourceBundle.en[ITEMTYPE_GLYPH_ARMOR] 			= "Armor Glyph (Enchanting)"
ResourceBundle.en[ITEMTYPE_GLYPH_JEWELRY] 			= "enITEMTYPE_GLYPH_JEWELRY"
ResourceBundle.en[ITEMTYPE_GLYPH_WEAPON] 			= "Weapon Glyph (Enchanting)"
ResourceBundle.en[ITEMTYPE_INGREDIENT] 				= "Ingredient (Provisioning)"
ResourceBundle.en[ITEMTYPE_LOCKPICK] 				= "enITEMTYPE_LOCKPICK"
ResourceBundle.en[ITEMTYPE_LURE] 					= "enITEMTYPE_LURE"
ResourceBundle.en[ITEMTYPE_NONE] 					= "enITEMTYPE_NONE"
ResourceBundle.en[ITEMTYPE_PLUG] 					= "enITEMTYPE_PLUG"
ResourceBundle.en[ITEMTYPE_POISON] 					= "enITEMTYPE_POISON"
ResourceBundle.en[ITEMTYPE_POTION] 					= "Potion"
ResourceBundle.en[ITEMTYPE_RAW_MATERIAL] 			= "enITEMTYPE_RAW_MATERIAL"
ResourceBundle.en[ITEMTYPE_REAGENT] 				= "Reagent (Alchemy)"
ResourceBundle.en[ITEMTYPE_RECIPE] 					= "enITEMTYPE_RECIPE"
ResourceBundle.en[ITEMTYPE_SCROLL] 					= "enITEMTYPE_SCROLL"
ResourceBundle.en[ITEMTYPE_SIEGE] 					= "enITEMTYPE_SIEGE"
ResourceBundle.en[ITEMTYPE_SOUL_GEM] 				= "Soul Gem"
ResourceBundle.en[ITEMTYPE_SPICE] 					= "enITEMTYPE_SPICE"
ResourceBundle.en[ITEMTYPE_STYLE_MATERIAL] 			= "Style Material"
ResourceBundle.en[ITEMTYPE_TABARD] 					= "enITEMTYPE_TABARD"
ResourceBundle.en[ITEMTYPE_TOOL] 					= "Tool"
ResourceBundle.en[ITEMTYPE_TRASH]					= "enITEMTYPE_TRASH"
ResourceBundle.en[ITEMTYPE_TROPHY] 					= "Trophy"
ResourceBundle.en[ITEMTYPE_WEAPON] 					= "enITEMTYPE_WEAPON"
ResourceBundle.en[ITEMTYPE_WEAPON_BOOSTER] 			= "enITEMTYPE_WEAPON_BOOSTER"
ResourceBundle.en[ITEMTYPE_WEAPON_TRAIT] 			= "Weapon Trait"
ResourceBundle.en[ITEMTYPE_WOODWORKING_BOOSTER] 	= "Resin (Woodworking)"
ResourceBundle.en[ITEMTYPE_WOODWORKING_MATERIAL] 	= "Material (Woodworking)"
ResourceBundle.en[ITEMTYPE_WOODWORKING_RAW_MATERIAL] = "Raw Material (Woodworking)"