if ResourceBundle == nil then ResourceBundle = {} end
if ResourceBundle.fr == nil then ResourceBundle.fr = {} end

-- Welcome Messages --								-- Type '/pa' for GUI."
ResourceBundle.fr["Welcome_NoSupport"] 				= PAC_COL_YELLOW.."P"..PAC_COL_WHITE.."ersonal"..PAC_COL_YELLOW.."A"..PAC_COL_WHITE.."ssistant"..PAC_COL_YELLOW.." at your service!   -   no localization for (%s) available yet."
ResourceBundle.fr["Welcome_Support"] 				= PAC_COL_YELLOW.."P"..PAC_COL_WHITE.."ersonal"..PAC_COL_YELLOW.."A"..PAC_COL_WHITE.."ssistant"..PAC_COL_YELLOW.." à votre service !"

-- PAGeneral --
ResourceBundle.fr["PAG_Profile1"]					= "Profil 1"
ResourceBundle.fr["PAG_Profile2"]					= "Profil 2"
ResourceBundle.fr["PAG_Profile3"]					= "Profil 3"

-- PARepair --
ResourceBundle.fr["PAR_FullRepair"] 				= "PARepair : Tous les objets %s ont été réparés pour %d pièces d'or."
ResourceBundle.fr["PAR_PartialRepair"] 				= "PARepair : %d / %d objets %s réparés pour %d pièces d'or. (Pas assez d'or)"
ResourceBundle.fr["PAR_NoGoldToRepair"] 			= "PARepair : Pas assez d'or pour réparer les %d objets %s."
ResourceBundle.fr["PAR_NoRepair"] 					= "PARepair : Rien à réparer."

-- PABanking --
ResourceBundle.fr["PAB_GoldDepositet"] 				= "PABanking : %d pièces d'or déposées."
ResourceBundle.fr["PAB_GoldWithdrawn"] 				= "PABanking : %d pièces d'or retirées."
ResourceBundle.fr["PAB_GoldWithdrawnInsufficient"] 	= "PABanking : %d / %d pièces d'or retirées. (Pas assez en banque !)"

ResourceBundle.fr["PAB_ItemMovedTo"] 				= "%d x %s déplacés vers %s."
ResourceBundle.fr["PAB_ItemNotMovedTo"] 			= "%d x %s n'ont PAS été déplacés vers %s."
ResourceBundle.fr["PAB_ItemMovedToFailed"] 			= "ÉCHEC : %s n'ont PAS pu être déplacés vers %s."

ResourceBundle.fr["PAB_NoSpaceInFor"] 				= "PABanking : Pas assez d'espace dans %s pour : %s."
ResourceBundle.fr["PAB_NoSpaceToOpen"] 				= "PABanking : Pas assez d'espace dans %s pour ouvrir %s."
ResourceBundle.fr["PAB_NoDeposit"] 					= "PABanking : Rien à déposer."

ResourceBundle.fr["PAB_ItemType_None"] 				= "-"
ResourceBundle.fr["PAB_ItemType_Deposit"]			= "Déposer"
ResourceBundle.fr["PAB_ItemType_Withdrawal"]		= "Retirer"
ResourceBundle.fr["PAB_ItemType_Inherit"]			= "Selon le type d'objet (ci-dessous)"

-- MainMenu --
ResourceBundle.fr["MMenu_Title"] 					= "|cFFD700P|rersonal|cFFD700A|rssistant"

-- PAGMenu --
ResourceBundle.fr["PAGMenu_Header"]					= "|cFFD700PA G|réneral"
ResourceBundle.fr["PAGMenu_ActiveProfile"]			= "Profil actif"
ResourceBundle.fr["PAGMenu_ActiveProfile_T"]		= "Sélectionner le profil à utiliser. Changer la sélection chargera automatiquement les paramètres. Les changements ci-dessous seront automatiquement sauvegardés dans le profil."
ResourceBundle.fr["PAGMenu_ActiveProfileRename"]	= "frPAGMenu_ActiveProfileRename"
ResourceBundle.fr["PAGMenu_ActiveProfileRename_T"]	= "frPAGMenu_ActiveProfileRename_T"
ResourceBundle.fr["PAGMenu_ActiveProfileRename_W"]	= "|cff0000(forcera un rechargement de l'interface)|r"
ResourceBundle.fr["PAGMenu_Welcome"] 				= "Afficher le message d'accueil"
ResourceBundle.fr["PAGMenu_Welcome_T"] 				= "Afficher le message d'accueil de l'addon après un chargement réussi ?"

-- PARMenu --
ResourceBundle.fr["PARMenu_Header"] 				= "|cFFD700PA R|repair"
ResourceBundle.fr["PARMenu_Enable"] 				= "|cB0B0FFActiver l'Auto Repair|r"
ResourceBundle.fr["PARMenu_Enable_T"] 				= "Activer la Réparation Automatique ?"
ResourceBundle.fr["PARMenu_RepairEq"] 				= "Réparer les objets équipés"
ResourceBundle.fr["PARMenu_RepairEq_T"] 			= "Réparer les objets équipés ?"
ResourceBundle.fr["PARMenu_RepairEqDura"] 			= "- Seuil de durabilité en %"
ResourceBundle.fr["PARMenu_RepairEqDura_T"] 		= "Réparer les objets équipés s'ils sont en-dessous du seuil de durabilité défini."
ResourceBundle.fr["PARMenu_RepairBa"]				= "Réparer les objets dans le sac"
ResourceBundle.fr["PARMenu_RepairBa_T"] 			= "Réparer les objets dans le sac à dos ?"
ResourceBundle.fr["PARMenu_RepairBaDura"] 			= "- Seuil de durabilité en %"
ResourceBundle.fr["PARMenu_RepairBaDura_T"] 		= "Réparer les objets dans le sac s'ils sont en-dessous du seuil de durabilité défini."
ResourceBundle.fr["PARMenu_HideNoRepair"] 			= "Masquer le message 'Rien à réparer'"
ResourceBundle.fr["PARMenu_HideNoRepair_T"] 		= "Masquer le message 'Rien à réparer'. Vous verrez toujours un message s'il y a quelque chose à réparer."
ResourceBundle.fr["PARMenu_HideAll"] 				= "Masquer TOUS les messages"
ResourceBundle.fr["PARMenu_HideAll_T"] 				= "Mode silencieux : Aucun message ne sera affiché. Vous ne verrez pas le coût de vos réparations."

-- PABMenu --
ResourceBundle.fr["PABMenu_Header"] 				= "|cFFD700PA B|ranking"
ResourceBundle.fr["PABMenu_Enable"] 				= "|cB0B0FFActiver l'Auto Banking|r"
ResourceBundle.fr["PABMenu_Enable_T"] 				= "Activer la dépose et le retrait automatique en banque ?"
ResourceBundle.fr["PABMenu_DepGold"] 				= "Déposer de l'or"
ResourceBundle.fr["PABMenu_DepGold_T"] 				= "Déposer automatiquement de l'or en banque ?"
ResourceBundle.fr["PABMenu_DepInterval"] 			= "- Intervalle entre deux déposes (sec)"
ResourceBundle.fr["PABMenu_DepInterval_T"] 			= "Temps minimum en secondes entre deux déposes automatiques d'or."
ResourceBundle.fr["PABMenu_DepInterval_W"] 			= "Nombre non valide --> Pas de temps minimum entre les déposes."
ResourceBundle.fr["PABMenu_DepGoldPerc"] 			= "- Or à déposer en %"
ResourceBundle.fr["PABMenu_DepGoldPerc_T"] 			= "Pourcentage maximum de votre or à déposer."
ResourceBundle.fr["PABMenu_DepGoldSteps"] 			= "- Déplacement d'or par tranche de :"
ResourceBundle.fr["PABMenu_DepGoldSteps_T"] 		= "Par tranche de combien l'or doit être déposé ou retiré ?"
ResourceBundle.fr["PABMenu_DepGoldKeep"] 			= "- Or minimum à garder sur soi"
ResourceBundle.fr["PABMenu_DepGoldKeep_T"] 			= "Quantité d'or minimum à toujours conserver sur votre personnage."
ResourceBundle.fr["PABMenu_DepGoldKeep_W"] 			= "Nombre non valide --> Aucun or ne sera conservé sur votre personnage."
ResourceBundle.fr["PABMenu_WitGoldMin"] 			= "- Retirer de l'or si en-dessous du minimum"
ResourceBundle.fr["PABMenu_WitGoldMin_T"] 			= "Retirer automatiquement de l'or de la banque quand le personnage en a moins que défini ci-dessus ?"
ResourceBundle.fr["PABMenu_DepWitItem"] 			= "Déposer et retirer des objets"
ResourceBundle.fr["PABMenu_DepWitItem_T"] 			= "Déposer et/ou retirer automatiquement des objets de la banque?"
ResourceBundle.fr["PABMenu_DepItemTypeDesc"] 		= "Définir les actions spécifiques (déposer, retirer, ignorer) pour les types d'objets communs et avancés."
ResourceBundle.fr["PABMenu_DepItemType"] 			= "Types d'objets communs"
ResourceBundle.fr["PABMenu_DepItemType_T"] 			= "Ouvrez le sous-menu pour définir pour chaque type d'objet s'il doit être déposer, retirer, ou ignorer."
ResourceBundle.fr["PABMenu_Advanced_DepItemType"]	= "Types d'objets avancés"
ResourceBundle.fr["PABMenu_Advanced_DepItemType_T"]	= "Ouvrez le sous-menu pour définir de façon avancée quels types d'objets doivent être déposés, retirés ou ignorés."
ResourceBundle.fr["PABMenu_DepItemTimerInterval"]	= "- Intervalle entre les déposes (msecs)"
ResourceBundle.fr["PABMenu_DepItemTimerInterval_T"]	= "Combien de temps en msecs entre deux déposes consécutives d'objets. Si la dépose de beaucoup d'objets ne fonctionne pas, pensez à augmenter cette valeur."
ResourceBundle.fr["PABMenu_ItemJunk_Header"]		= PAC_COL_LIGHT_BLUE.."OBJETS NOTÉS AU REBUT"
ResourceBundle.fr["PABMenu_DepItemJunk"] 			= "Objets au rebut"
ResourceBundle.fr["PABMenu_DepItemJunk_T"] 			= "Est-ce que tous les items au rebut, seulement ceux de type d'objets ci-dessous ou aucun doivent être retirés ou déposés en banque ?"
ResourceBundle.fr["PABMenu_ItemType_Header"]		= PAC_COL_LIGHT_BLUE.."TYPES D'OBJET"
ResourceBundle.fr["PABMenu_HideNoDeposit"] 			= "Masquer le message 'Rien à déposer'"
ResourceBundle.fr["PABMenu_HideNoDeposit_T"] 		= "Masquer le message 'Rien à déposer'. Vous verrez un message s'il a quelque chose à déposer."
ResourceBundle.fr["PABMenu_HideAll"] 				= "Masquer TOUS les messages"
ResourceBundle.fr["PABMenu_HideAll_T"] 				= "Mode silencieux : Aucun message ne sera affiché. Vous ne verrez pas vos objets/or déposés."
ResourceBundle.fr["PABMenu_DepButton"] 				= "Tout déposer"
ResourceBundle.fr["PABMenu_DepButton_T"] 			= "Changer toutes les valeurs de menu pour 'Déposer'?"
ResourceBundle.fr["PABMenu_WitButton"] 				= "Tout retirer"
ResourceBundle.fr["PABMenu_WitButton_T"] 			= "Changer toutes les valeurs de menu pour 'Retirer'?"
ResourceBundle.fr["PABMenu_IgnButton"] 				= "Tout ignorer"
ResourceBundle.fr["PABMenu_IgnButton_T"] 			= "Changer toutes les valeurs de menu pour '-'?"

-- Name Spaces --
ResourceBundle.fr["NS_Bag_Equipment"]				= ""	-- not required so far
ResourceBundle.fr["NS_Bag_Equipped"]				= "équipés"
ResourceBundle.fr["NS_Bag_Backpack"]				= "le sac à dos"
ResourceBundle.fr["NS_Bag_Backpacked"]				= "dans le sac à dos"
ResourceBundle.fr["NS_Bag_Bank"]					= "la banque"
ResourceBundle.fr["NS_Bag_Banked"]					= ""	-- not required so far
ResourceBundle.fr["NS_Bag_Unknown"]					= "inconnu"

-- Item Types --
ResourceBundle.fr[ITEMTYPE_ADDITIVE] 				= "frITEMTYPE_ADDITIVE"
ResourceBundle.fr[ITEMTYPE_ALCHEMY_BASE] 			= "Solvant (Alchimie)"
ResourceBundle.fr[ITEMTYPE_ARMOR] 					= "Armure"
ResourceBundle.fr[ITEMTYPE_ARMOR_BOOSTER] 			= "frITEMTYPE_ARMOR_BOOSTER"
ResourceBundle.fr[ITEMTYPE_ARMOR_TRAIT] 			= "Caractéristique d'armure"
ResourceBundle.fr[ITEMTYPE_AVA_REPAIR] 				= "frITEMTYPE_AVA_REPAIR"
ResourceBundle.fr[ITEMTYPE_BLACKSMITHING_BOOSTER] 	= "Trempe (Forge)"
ResourceBundle.fr[ITEMTYPE_BLACKSMITHING_MATERIAL] 	= "Matériau (Forge)"
ResourceBundle.fr[ITEMTYPE_BLACKSMITHING_RAW_MATERIAL] = "Matériau brut (Forge)"
ResourceBundle.fr[ITEMTYPE_CLOTHIER_BOOSTER] 		= "Tanin (Couture)"
ResourceBundle.fr[ITEMTYPE_CLOTHIER_MATERIAL] 		= "Matière (Couture)"
ResourceBundle.fr[ITEMTYPE_CLOTHIER_RAW_MATERIAL] 	= "Matière brute (Couture)"
ResourceBundle.fr[ITEMTYPE_COLLECTIBLE] 			= "frITEMTYPE_COLLECTIBLE"
ResourceBundle.fr[ITEMTYPE_CONTAINER] 				= "Récipient"
ResourceBundle.fr[ITEMTYPE_COSTUME] 				= "Costume"
ResourceBundle.fr[ITEMTYPE_DISGUISE] 				= "frITEMTYPE_DISGUISE"
ResourceBundle.fr[ITEMTYPE_DRINK] 					= "Boisson"
ResourceBundle.fr[ITEMTYPE_ENCHANTING_RUNE_ASPECT]	= "Aspect Pierre runique d'Aspect (Enchantement)"
ResourceBundle.fr[ITEMTYPE_ENCHANTING_RUNE_ESSENCE]	= "Essence Pierre runique d'Essence (Enchantement)"
ResourceBundle.fr[ITEMTYPE_ENCHANTING_RUNE_POTENCY]	= "Puissance Pierre runique de Puissance (Enchantement)"
ResourceBundle.fr[ITEMTYPE_ENCHANTMENT_BOOSTER] 	= "frITEMTYPE_ENCHANTMENT_BOOSTER"
ResourceBundle.fr[ITEMTYPE_FLAVORING] 				= "frITEMTYPE_FLAVORING"
ResourceBundle.fr[ITEMTYPE_FOOD] 					= "Nourriture"
ResourceBundle.fr[ITEMTYPE_GLYPH_ARMOR] 			= "Glyphe d'armure (Enchantement)"
ResourceBundle.fr[ITEMTYPE_GLYPH_JEWELRY] 			= "Glyphe de bijou (Enchantement)"
ResourceBundle.fr[ITEMTYPE_GLYPH_WEAPON] 			= "Glyphe d'arme (Enchantement)"
ResourceBundle.fr[ITEMTYPE_INGREDIENT] 				= "Ingrédient (Cuisine)"
ResourceBundle.fr[ITEMTYPE_LOCKPICK] 				= "Crochetage"
ResourceBundle.fr[ITEMTYPE_LURE] 					= "Appât"
ResourceBundle.fr[ITEMTYPE_MOUNT]					= "frITEMTYPE_MOUNT"
ResourceBundle.fr[ITEMTYPE_NONE] 					= "frITEMTYPE_NONE"
ResourceBundle.fr[ITEMTYPE_PLUG] 					= "frITEMTYPE_PLUG"
ResourceBundle.fr[ITEMTYPE_POISON] 					= "frITEMTYPE_POISON"
ResourceBundle.fr[ITEMTYPE_POTION] 					= "Potion"
ResourceBundle.fr[ITEMTYPE_RAW_MATERIAL] 			= "Matériau brut"
ResourceBundle.fr[ITEMTYPE_REAGENT] 				= "Réactif (Alchimie)"
ResourceBundle.fr[ITEMTYPE_RECIPE] 					= "Recette (Cuisine)"
ResourceBundle.fr[ITEMTYPE_RACIAL_STYLE_MOTIF] 		= "frITEMTYPE_RACIAL_STYLE_MOTIF"
ResourceBundle.fr[ITEMTYPE_SIEGE] 					= "frITEMTYPE_SIEGE"
ResourceBundle.fr[ITEMTYPE_SOUL_GEM] 				= "Pierre d'âme"
ResourceBundle.fr[ITEMTYPE_SPICE] 					= "frITEMTYPE_SPICE"
ResourceBundle.fr[ITEMTYPE_STYLE_MATERIAL] 			= "Matériau de style"
ResourceBundle.fr[ITEMTYPE_TABARD] 					= "frITEMTYPE_TABARD"
ResourceBundle.fr[ITEMTYPE_TOOL] 					= "Outil"
ResourceBundle.fr[ITEMTYPE_TRASH]					= "Camelote"
ResourceBundle.fr[ITEMTYPE_TROPHY] 					= "Trophée"
ResourceBundle.fr[ITEMTYPE_WEAPON] 					= "frITEMTYPE_WEAPON"
ResourceBundle.fr[ITEMTYPE_WEAPON_BOOSTER] 			= "frITEMTYPE_WEAPON_BOOSTER"
ResourceBundle.fr[ITEMTYPE_WEAPON_TRAIT] 			= "Caractéristique d'arme"
ResourceBundle.fr[ITEMTYPE_WOODWORKING_BOOSTER] 	= "Résine (Travail du bois)"
ResourceBundle.fr[ITEMTYPE_WOODWORKING_MATERIAL] 	= "Matériau (Travail du bois)"
ResourceBundle.fr[ITEMTYPE_WOODWORKING_RAW_MATERIAL] = "Matériau brut (Travail du bois)"