PersonalAssistant.Localization = {
    -- Type '/pa' for GUI."
    -- Welcome Messages --
    Welcome_NoSupport = PAC_COLTEXT_PA .. PAC_COL_DEFAULT .. " at your service!   -   no localization for language [%s] available (yet).",
    Welcome_Support = PAC_COLTEXT_PA .. PAC_COL_DEFAULT .. " at your service!",
    Welcome_PleaseSelectProfile = PAC_COLTEXT_PA .. PAC_COL_DEFAULT .. " welcomes you! In order to get started, please go to the Addon Settings (or type /pa) and select a profile. Thank you :-)",

    -- Key Bindings
    KB_Load_Profile1 = "Activate profile 1",
    KB_Load_Profile2 = "Activate profile 2",
    KB_Load_Profile3 = "Activate profile 3",
    KB_Load_Profile4 = "Activate profile 4",
    KB_Load_Profile5 = "Activate profile 5",

    -- PAGeneral --
    PAG_Profile1 = "Profile 1",
    PAG_Profile2 = "Profile 2",
    PAG_Profile3 = "Profile 3",
    PAG_Profile4 = "Profile 4",
    PAG_Profile5 = "Profile 5",
    PAG_PleaseSelectProfile = "<Please select Profile>",

    -- PARepair Chat Output - Full Repair --
    PAR_FullRepair_ChatMode_None = "<no output>",
    PAR_FullRepair_ChatMode_Min = PAC_COL_RED .. "- %d " .. PAC_ICON_GOLD,
    PAR_FullRepair_ChatMode_Normal = PAC_COLTEXT_PAR .. PAC_COL_RED .. "- %d " .. PAC_ICON_GOLD,
    PAR_FullRepair_ChatMode_Full = PAC_COLTEXT_PAR .. "All %s items repaired for " .. PAC_COL_RED .. "- %d " .. PAC_ICON_GOLD,

    -- PARepair Chat Output - Partial Repair --
    PAR_PartialRepair_ChatMode_None = "<no output>",
    PAR_PartialRepair_ChatMode_Min = PAC_COL_RED .. "- %d " .. PAC_ICON_GOLD .. PAC_COL_DEFAULT .. " (%d " .. PAC_ICON_GOLD .. ")",
    PAR_PartialRepair_ChatMode_Normal = PAC_COLTEXT_PAR .. PAC_COL_RED .. "- %d " .. PAC_ICON_GOLD .. PAC_COL_DEFAULT .. " (%d " .. PAC_ICON_GOLD .. " missing)",
    PAR_PartialRepair_ChatMode_Full = PAC_COLTEXT_PAR .. "%d / %d %s items repaired for " .. PAC_COL_RED .. "- %d " .. PAC_ICON_GOLD .. PAC_COL_DEFAULT .. " (%d " .. PAC_ICON_GOLD .. " missing for full repair)",

    -- PARepair Chat Output - Weapon Charge --
    PAR_ReChargeWeapon_ChatMode_None = "<no output>",
    PAR_ReChargeWeapon_ChatMode_Min = PAC_COL_DEFAULT .. "%s %s (%d%% --> %d%%)",
    PAR_ReChargeWeapon_ChatMode_Normal = PAC_COLTEXT_PAR .. "%s (%d%% --> %d%%) - %s",
    PAR_ReChargeWeapon_ChatMode_Full = PAC_COLTEXT_PAR .. "Charged %s %s from %d%% to %d%%  with %s %s",

    -- PABanking --
    PAB_GoldDeposited = PAC_COLTEXT_PAB .. "%d " .. PAC_ICON_GOLD .. " deposited.",
    PAB_GoldWithdrawn = PAC_COLTEXT_PAB .. "%d " .. PAC_ICON_GOLD .. " withdrawn.",
    PAB_GoldWithdrawnInsufficient = PAC_COLTEXT_PAB .. "%d / %d " .. PAC_ICON_GOLD .. " withdrawn. (not enough gold in bank!)",
    PAB_ItemMovedTo = PAC_COLTEXT_PAB .. "%d x %s moved to %s.",
    PAB_ItemNotMovedTo = PAC_COLTEXT_PAB .. "%d x %s NOT moved to %s.",
    PAB_ItemMovedToFailed = PAC_COLTEXT_PAB .. PAC_COL_ORANGE .. "FAILURE: %s could NOT be moved to %s.",
    PAB_NoSpaceInFor = PAC_COLTEXT_PAB .. PAC_COL_ORANGE .. "Not enough space in %s for: %s.",
    PAB_NoDeposit = PAC_COLTEXT_PAB .. "Nothing to deposit.",
    PAB_ItemType_None = "-",
    PAB_ItemType_Deposit = "Deposit",
    PAB_ItemType_Withdrawal = "Withdraw",
    PAB_ItemType_Inherit = "Depending on item type (below)",
    PAB_MoveTo_Ignore = "Ignore",
    PAB_MoveTo_Bank = "Deposit to Bank",
    PAB_MoveTo_Backpack = "Withdraw to Backpack",

    -- PALoot --
    PAL_ItemType_Ignore = "Ignore",
    PAL_ItemType_AutoLoot = "Auto-Loot",
    PAL_ItemType_LootDestroy = "Auto-Loot and " .. PAC_COL_RED .. "Destroy",
    PAL_RecipeUnknown_Suffix = "(unknown)",
    PAL_ItemType_Ignore_T = "Nothing happens, the item is ignored",
    PAL_ItemType_AutoLoot_T = "Automatically loots the item",
    PAL_ItemType_LootDestroy_T = PAC_COL_RED .. "CAUTION: USE AT OWN RISK!|r Automatically loots the item, but then immediately destroys the looted amount again.",

    -- PALoot Chat Output - Loot Gold --
    PAL_Gold_ChatMode_None = "<no output>",
    PAL_Gold_ChatMode_Min = PAC_COL_GREEN .. "+ %d " .. PAC_ICON_GOLD,
    PAL_Gold_ChatMode_Normal = PAC_COLTEXT_PAL .. PAC_COL_GREEN .. "+ %d " .. PAC_ICON_GOLD,
    PAL_Gold_ChatMode_Full = PAC_COLTEXT_PAL .. "Looted " .. PAC_COL_GREEN .. "+ %d " .. PAC_ICON_GOLD .. PAC_COL_DEFAULT .. " Gold",

    -- PALoot Chat Output - Loot Items --
    PAL_Items_ChatMode_None = "<no output>",
    PAL_Items_ChatMode_Min = PAC_COL_DEFAULT .. "%d x %s %s",
    PAL_Items_ChatMode_Normal = PAC_COL_DEFAULT .. "%d x %s %s %s",
    PAL_Items_ChatMode_Full = PAC_COLTEXT_PAL .. "%d x %s %s %s",

    -- PALoot Chat Output - Loot Items Destroyed--
    PAL_ItemsDestroy_Min = PAC_COL_DEFAULT .. "%d x %s destroyed",
    PAL_ItemsDestroy_Normal = PAC_COL_DEFAULT .. "%d x %s %s destroyed",
    PAL_ItemsDestroy_Full = PAC_COLTEXT_PAL .. "%d x %s %s have been destroyed",
    PAL_ItemsDestroy_MoveFailed = PAC_COLTEXT_PAL .. PAC_COL_ORANGE .. "FAILURE: Could NOT split %d/%d %s %s into seperate stack to destroy safely",
    PAL_ItemsDestroy_DestroyFailed = PAC_COLTEXT_PAL .. PAC_COL_ORANGE .. "FAILURE: No free inventory slot to safely destroy %d/%d %s %s",

    -- PAJunk --
    PAJ_MarkedAsJunk = PAC_COLTEXT_PAJ .. "Marked %s as junk",
    PAJ_SoldJunkInfo = PAC_COLTEXT_PAJ .. "Sold junk items for " .. PAC_COL_GREEN .. "%d " .. PAC_ICON_GOLD,

    -- MainMenu --
    MMenu_Title = PAC_COLTEXT_PA,

    -- PAGMenu --
    PAGMenu_Header = PAC_COLTEXT_PAG,
    PAGMenu_ActiveProfile = "Active profile",
    PAGMenu_ActiveProfile_T = "Select the profile settings that shall be used. Changing the selection will automatically load the settings. Changes below will automatically be stored under the profile.",
    PAGMenu_ActiveProfileRename = "Rename active profile",
    PAGMenu_ActiveProfileRename_T = "Rename the active profile",
    PAGMenu_Welcome = "Show welcome message",
    PAGMenu_Welcome_T = "Display a welcome message from the addon upon successfully starting?",

    -- PARMenu --
    PARMenu_Header = PAC_COLTEXT_PAR,
    PARMenu_Enable = PAC_COL_LIGHT_BLUE .. "Enable Auto Repair",
    PARMenu_Enable_T = "Enable Auto Repair?",
    PARMenu_RepairWornGold = "Repair equipped items",
    PARMenu_RepairWornGold_T = "Repair equipped items at a merchant?",
    PARMenu_RepairWornGoldDura = "- Durability threshold in %",
    PARMenu_RepairWornGoldDura_T = "Repair equipped items only if they are at or below the defined durability threshold.",
    PARMenu_RepairWornKit = "Use Repair Kits",
    PARMenu_RepairWornKit_T = "Repair equipped items with repair kits when out in the field? (Common repair kits will be used before greater ones)",
    PARMenu_RepairWornKitDura = "- Durability threshold in %",
    PARMenu_RepairWornKitDura_T = "Equipped items will only be repaired with a repair kit when their durability is at or below the defined threshold",
    PARMenu_RepairFullChatMode = "Chat display: Full repairs",
    PARMenu_RepairFullChatMode_T = "How to display the information of a full repair in the chat window",
    PARMenu_RepairPartialChatMode = "Chat display: Partial/incomplete repairs",
    PARMenu_RepairPartialChatMode_T = "How to display the information of an incomplet or parcial repair i.e. due to insufficient gold) in the chat window",
    PARMenu_ChargeWeapons = "Re-Charge Weapons",
    PARMenu_ChargeWeapons_T = "Re-Charge equipped weapons?",
    PARMenu_ChargeWeaponsDura = "- Re-Charge threshold in %",
    PARMenu_ChargeWeaponsDura_T = "Re-Charge equipped weapons when their charge level is at or below the defined threshold. (Lesser soul gems will be used before common ones)",
    PARMenu_ChargeWeaponsChatMode = "Chat display: Charging weapons",
    PARMenu_ChargeWeaponsChatMode_T = "How to display the information of a re-charged weapon in the chat window",

    -- PABMenu --
    PABMenu_Header = PAC_COLTEXT_PAB,
    PABMenu_Enable = PAC_COL_LIGHT_BLUE .. "Enable Auto Banking",
    PABMenu_Enable_T = "Enable Auto Bank Deposit and Withdrawal?",
    PABMenu_EnabledGold = "Deposit Gold",
    PABMenu_EnabledGold_T = "Auto deposit gold to bank?",
    PABMenu_GoldTransactionStep = "- Gold transactions in steps of ",
    PABMenu_GoldTransactionStep_T = "In what steps shall gold be deposited and withdrawn?",
    PABMenu_GoldMinToKeep = "- Min gold to keep on character",
    PABMenu_GoldMinToKeep_T = "Minimum amount of gold to always keep on the character.",
    PABMenu_GoldMinToKeep_W = "Invalid number --> No gold shall be kept on the character.",
    PABMenu_WithdrawToMinGold = "- Withdraw gold if below minimum",
    PABMenu_WithdrawToMinGold_T = "Automatically withdraw gold from the bank if there is less gold on the character than defined above?",
    PABMenu_EnabledItems = "Deposit and withdraw items",
    PABMenu_EnabledItems_T = "Auto deposit and/or withdraw items to and from the bank?",
    PABMenu_DepItemTypeDesc = "Define an individual behaviour (deposit, withdraw, ignore) for common item types as well as more advanced ones.",
    PABMenu_ItemTypeMaterialSubmenu = "Crafting Material",
    PABMenu_ItemTypeMaterialESOPlusDesc = PAC_COL_LIGHT_BLUE .. "As an ESO Plus Member, the deposit/withdrawal of Crafting Materials is not relevant since all of them can be carried with an infinite amount in the Craft Bag.",
    PABMenu_DepItemType = "Common item types",
    PABMenu_DepItemType_T = "Open the sub-menu to define for each item type whether it shall be deposited, withdrawn or ignored.",
    PABMenu_DepStackOnly = "Stacking type (Deposit)",
    PABMenu_DepStackOnly_T = "Define whether all matching items shall be deposited completely, if only items that exist in the target container shall be deposited or if only existing stacks shall be filled up to their max size.",
    PABMenu_WitStackOnly = "Stacking type (Withdraw)",
    PABMenu_WitStackOnly_T = "Define whether all matching items shall be withdrawn completely, if only items that exist in the target container shall be withdrawn or if only existing stacks shall be filled up to their max size.",
    PABMenu_Advanced_DepItemType = "Advanced item types",
    PABMenu_Advanced_DepItemType_T = "Open the sub-menu to define for other item types on an advanced level whether they shall be deposited, withdrawn or ignored.",
    PABMenu_DepItemTimerInterval = "- Interval between item deposits (msecs)",
    PABMenu_DepItemTimerInterval_T = "How many msecs shall pass between two consecutive item deposits. If too many item deposits don't work, consider increasing this value.",
    PABMenu_ItemType_Header = PAC_COL_LIGHT_BLUE .. "ITEM TYPES",
    PABMenu_HideNoDeposit = "Hide 'Nothing to Deposit' message",
    PABMenu_HideNoDeposit_T = "Hide 'Nothing to Deposit' message. You will see a message if there is something to deposit, though.",
    PABMenu_HideAll = "Hide ALL banking messages",
    PABMenu_HideAll_T = "Silent-Mode: No banking message will be displayed. You also won't see your deposited gold/items.",
    PABMenu_DepButton = "Deposit all",
    PABMenu_DepButton_T = "Change all dropdown values to 'Deposit'",
    PABMenu_WitButton = "Withdraw all",
    PABMenu_WitButton_T = "Change all dropdown values to 'Withdraw'",
    PABMenu_IgnButton = "Ignore all",
    PABMenu_IgnButton_T = "Change all dropdown values to '-'",
    PABMenu_Lockipck_Header = PAC_COL_LIGHT_BLUE .. "Lockpicks",
    PABMenu_Keep_in_Backpack = "Amount to keep in backpack",
    PABMenu_Keep_in_Backpack_T = "Define the amount which shall together with the mathematical operator be kept in the backpack.",

    -- PALMenu --
    PALMenu_Header = PAC_COLTEXT_PAL,
    PALMenu_Enable = PAC_COL_LIGHT_BLUE .. "Enable Auto Loot",
    PALMenu_Enable_T = "Enable Auto Loot?",
    PALMenu_LootGold = "Auto-Loot gold",
    PALMenu_LootGold_T = "Automatically loot gold?",
    PALMenu_LootGoldChatMode = "Chat Display of Auto-Looted Gold",
    PALMenu_LootGoldChatMode_T = "How to display the information of looted gold in the chat window",
    PALMenu_LootItems = "Auto-Loot items",
    PALMenu_LootItems_T = "Automatically loot items?",
    PALMenu_LootItemsChatMode = "Chat Display of Auto-Looted Items",
    PALMenu_LootItemsChatMode_T = "How to display the information of looted items in the chat window",
    PALMenu_LootStolenItems = "Auto-Steal items",
    PALMenu_LootStolenItems_T = "Include (to be) stolen items for the Auto-Loot?",
    PALMenu_HarvestableItems = "Harvestable items",
    PALMenu_HarvestableItems_T = "Open the sub-menu to define for each harvestable item type whether it shall be auto-looted or not.",
    PALMenu_HarvestableItemsDesc = "Enable and disable auto-loot for harvestable items such as ores, herbs, woods, runestones, or fishing holes.",
    PALMenu_HarvestableItems_Bait_Header = PAC_COL_LIGHT_BLUE .. "BAIT HANDLING",
    PALMenu_HarvestableItems_Bait = "Handling of [Bait] items",
    PALMenu_HarvestableItems_Bait_T = "When looting harvestable items, sometimes there also is bait which prevents the node from re-spawning when not looted. Define here what should happen in such cases.",
    PALMenu_HarvestableItems_Header = PAC_COL_LIGHT_BLUE .. "ITEM TYPES",
    PALMenu_LootableItems = "Lootable items",
    PALMenu_LootableItems_T = "Open the sub-menu to define for each lootable item type whether it shall be auto-looted or not.",
    PALMenu_LootableItemsDesc = "Enable and disable auto-loot for lootable items such as clothing raw materials from animals.",
    PALMenu_LootableItems_Header = PAC_COL_LIGHT_BLUE .. "ITEM TYPES",
    PALMenu_AutoLootQuestItems = "Quest Items",
    PALMenu_AutoLootLockpicks = "Lockpick",
    PALMenu_AutoLootAllButton = "Auto-Loot all",
    PALMenu_AutoLootAllButton_T = "Change all dropdown values to 'Auto-Loot'",
    PALMenu_IgnButton = "Ignore all",
    PALMenu_IgnButton_T = "Change all dropdown values to 'Ignore'",

    -- PAJMenu --
    PAJMenu_Header = PAC_COLTEXT_PAJ,
    PAJMenu_Enable = PAC_COL_LIGHT_BLUE .. "Enable Auto Junk",
    PAJMenu_Enable_T = "Enable Auto Junk?",
    PAJMenu_ItemTypeDesc = "Enable and disable the automatic marking as junk for different item types.",
    PAJMenu_AutoSellJunk = "Auto-Sell Junk?",
    PAJMenu_AutoSellJunk_T = "Automatically sell all items marked as junk?",
    PAJMenu_AutoMarkTrash = "Auto-Mark [Trash]",
    PAJMenu_AutoMarkTrash_T = "Automatically mark items of type [Trash] as junk?",
    PAJMenu_AutoMarkOrnate = "Auto-Mark [Ornate] trait",
    PAJMenu_AutoMarkOrnate_T = "Automatically mark items with [Ornate] trait as junk?",

    -- Name Spaces --
    NS_Bag_Equipment = "", -- not required so far
    NS_Bag_Equipped = "equipped",
    NS_Bag_Backpack = "backpack",
    NS_Bag_Backpacked = "backpack",
    NS_Bag_Bank = "bank",
    NS_Bag_Banked = "", -- not required so far
    NS_Bag_Unknown = "unknown",

    -- Operators --
    REL_Operator = "Mathematical Operator",
    REL_None = "-",
    REL_Equal = "equals (=)",
    REL_LessThan = "less than (<)", -- not required so far
    REL_LessThanEqual = "less than or equal to (<=)",
    REL_GreaterThan = "greater than (>)", -- not required so far
    REL_GreaterThanEqual = "greater than or equal to (>=)",

    -- Stacking types --
    ST_MoveAllFull = "Move everything", -- 0: Full deposit
    ST_MoveExistingFull = "Move all if a stack exists", -- 1: Deposit if existing
    ST_FillIncompleteOnly = "Only fill up existing stacks", -- 2: Fill existing stacks

    -- Official Item Types --
    -- TODO: fixme; problem is we need resolved value of "ITEMTYPE_ADDITIVE" as key and not the string itself
    ITEMTYPE_ADDITIVE = "enITEMTYPE_ADDITIVE",
    ITEMTYPE_ARMOR = "Armor (any)",
    ITEMTYPE_ARMOR_BOOSTER = "enITEMTYPE_ARMOR_BOOSTER",
    ITEMTYPE_ARMOR_TRAIT = "Armor Trait",
    ITEMTYPE_AVA_REPAIR = "enITEMTYPE_AVA_REPAIR",
    ITEMTYPE_BLACKSMITHING_BOOSTER = "Temper (Blacksmithing)",
    ITEMTYPE_BLACKSMITHING_MATERIAL = "Material (Blacksmithing)",
    ITEMTYPE_BLACKSMITHING_RAW_MATERIAL = "Raw Material (Blacksmithing)",
    ITEMTYPE_CLOTHIER_BOOSTER = "Tannin (Clothing)",
    ITEMTYPE_CLOTHIER_MATERIAL = "Material (Clothing)",
    ITEMTYPE_CLOTHIER_RAW_MATERIAL = "Raw Material (Clothing)",
    ITEMTYPE_COLLECTIBLE = "Collectible",
    ITEMTYPE_CONTAINER = "Container",
    ITEMTYPE_COSTUME = "Costume",
    ITEMTYPE_CROWN_ITEM = "enITEMTYPE_CROWN_ITEM",
    ITEMTYPE_CROWN_REPAIR = "enITEMTYPE_CROWN_REPAIR",
    ITEMTYPE_DEPRECATED = "enITEMTYPE_DEPRECATED",
    ITEMTYPE_DISGUISE = "enITEMTYPE_DISGUISE",
    ITEMTYPE_DRINK = "Drink",
    ITEMTYPE_ENCHANTING_RUNE_ASPECT = "Aspect Runestone (Enchanting)",
    ITEMTYPE_ENCHANTING_RUNE_ESSENCE = "Essence Runestone (Enchanting)",
    ITEMTYPE_ENCHANTING_RUNE_POTENCY = "Potency Runestone (Enchanting)",
    ITEMTYPE_ENCHANTMENT_BOOSTER = "enITEMTYPE_ENCHANTMENT_BOOSTER",
    ITEMTYPE_FISH = "Fish",
    ITEMTYPE_FLAVORING = "enITEMTYPE_FLAVORING",
    ITEMTYPE_FOOD = "Food",
    ITEMTYPE_FURNISHING_MATERIAL = "Furnishing Material",
    ITEMTYPE_GLYPH_ARMOR = "Armor Glyph (Enchanting)",
    ITEMTYPE_GLYPH_JEWELRY = "Jewelry Glyph (Enchanting)",
    ITEMTYPE_GLYPH_WEAPON = "Weapon Glyph (Enchanting)",
    ITEMTYPE_INGREDIENT = "Ingredient (Provisioning)",
    ITEMTYPE_LOCKPICK = "enITEMTYPE_LOCKPICK",
    ITEMTYPE_LURE = "Bait",
    ITEMTYPE_MASTER_WRIT = "enITEMTYPE_MASTER_WRIT",
    ITEMTYPE_MAX_VALUE = "enITEMTYPE_MAX_VALUE",
    ITEMTYPE_MIN_VALUE = "enITEMTYPE_MIN_VALUE",
    ITEMTYPE_MOUNT = "enITEMTYPE_MOUNT",
    ITEMTYPE_NONE = "enITEMTYPE_NONE",
    ITEMTYPE_PLUG = "enITEMTYPE_PLUG",
    ITEMTYPE_POISON = "Poison",
    ITEMTYPE_POISON_BASE = "Poison Solvent (Alchemy)",
    ITEMTYPE_POTION = "Potion",
    ITEMTYPE_POTION_BASE = "Potion Solvent (Alchemy)",
    ITEMTYPE_RACIAL_STYLE_MOTIF = "Motif",
    ITEMTYPE_RAW_MATERIAL = "Raw Material",
    ITEMTYPE_REAGENT = "Reagent (Alchemy)",
    ITEMTYPE_RECIPE = "Recipe (Provisioning)",
    ITEMTYPE_SIEGE = "enITEMTYPE_SIEGE",
    ITEMTYPE_SOUL_GEM = "Soul Gem",
    ITEMTYPE_SPELLCRAFTING_TABLET = "enITEMTYPE_SPELLCRAFTING_TABLET",
    ITEMTYPE_SPICE = "enITEMTYPE_SPICE",
    ITEMTYPE_STYLE_MATERIAL = "Style Material",
    ITEMTYPE_TABARD = "enITEMTYPE_TABARD",
    ITEMTYPE_TOOL = "Tool",
    ITEMTYPE_TRASH = "Trash",
    ITEMTYPE_TREASURE = "enITEMTYPE_TREASURE",
    ITEMTYPE_TROPHY = "Trophy",
    ITEMTYPE_WEAPON = "Weapon (any)",
    ITEMTYPE_WEAPON_BOOSTER = "enITEMTYPE_WEAPON_BOOSTER",
    ITEMTYPE_WEAPON_TRAIT = "Weapon Trait",
    ITEMTYPE_WOODWORKING_BOOSTER = "Resin (Woodworking)",
    ITEMTYPE_WOODWORKING_MATERIAL = "Material (Woodworking)",
    ITEMTYPE_WOODWORKING_RAW_MATERIAL = "Raw Material (Woodworking)"
}
