--
-- Created by IntelliJ IDEA.
-- User: Klingo
-- Date: 25.02.2017
-- Time: 19:56
--

-- Ideas:
-- Auto-Deconstruct Items based on their quality level
-- Auto-Decosntruct Items with [Intricate] item trait
-- Auto Refine Crafting material