ZO_CreateStringId("SI_BINDING_NAME_ACTIVATE_PROFILE_1", PAL.getResourceMessage("KB_Load_Profile1"))
ZO_CreateStringId("SI_BINDING_NAME_ACTIVATE_PROFILE_2", PAL.getResourceMessage("KB_Load_Profile2"))
ZO_CreateStringId("SI_BINDING_NAME_ACTIVATE_PROFILE_3", PAL.getResourceMessage("KB_Load_Profile3"))
ZO_CreateStringId("SI_BINDING_NAME_ACTIVATE_PROFILE_4", PAL.getResourceMessage("KB_Load_Profile4"))
ZO_CreateStringId("SI_BINDING_NAME_ACTIVATE_PROFILE_5", PAL.getResourceMessage("KB_Load_Profile5"))